### ISSUE TITLE
Browser doesn't use QUIC to connect to nginx

### ISSUE THREAD

**Issue by pinjiang** [bilibili/nginx_quic_module#2]
Aftere successfully compiled the quic_stack and quic_module for nginx, setup the nginx server at localhost.
But the browser doesn't connect with quic. The http response header contains  alt-svc: quic=":443"; ma=600; v="50,46,43", doesn't redirect the browser to use quic. 

The Chrome version used is 109.0.5414.120, I found it use quic and h3 with cloudflare-quic website, the response header is : alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400. 

--2023-01-25 17:13:02--  https://127.0.0.1/
Connecting to 127.0.0.1:443... connected.
WARNING: cannot verify 127.0.0.1's certificate, issued by ‘CN=QUIC Server Root CA’:
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Server: nginx/1.18.0
  Date: Wed, 25 Jan 2023 09:13:02 GMT
  Content-Type: text/html
  Content-Length: 2559
  Last-Modified: Mon, 23 Jan 2023 14:58:17 GMT
  Connection: keep-alive
  ETag: "63cea089-9ff"
  alt-svc: quic=":443"; ma=600; v="50,46,43"
  Accept-Ranges: bytes

**Comment by MacroLau** [comment]
emm，will fix it , we should response header as alt-svc: h3=":443"; ......

**Comment by MacroLau** [comment]
We have fixed it，pls try again
